vich_uploader:
    db_driver: orm

    mappings:
        agence_image:
            uri_prefix: /images/agence
            upload_destination: '%kernel.project_dir%/public/images/agence'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        background_image:
            uri_prefix: /images/background
            upload_destination: '%kernel.project_dir%/public/images/background'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        background_logo:
            uri_prefix: /images/background
            upload_destination: '%kernel.project_dir%/public/images/background'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
